name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  dev-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: '9'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run format -- --check
      - run: pnpm run typecheck
      - run: pnpm audit --prod --audit-level=high || true
      - run: pnpm vitest run --coverage --coverage.reporter=text --coverage.branches --coverage.statements --coverage.failUnder=75
      - run: pnpm vitest run -m property
      - run: pnpm playwright install --with-deps --dry-run
      - run: pnpm playwright test --reporter=line
      - run: npx stryker run --coverageAnalysis=perTest --threshold-break 60
